baseurl.api=http://192.168.124.24:8092
#baseurl.api=http://localhost:8092

# Bearer token — mora da odgovara RAF_AUTH_TOKEN env varijabli na serveru.
# Azurirati pre svakog build-a plugina.
auth.token=b4d8d3659020957d952c53b5302b4444aa1d733304f144aab4ca225847cd0649