server.port=8091
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://localhost:3306/raflms?serverTimezone=UTC
spring.datasource.username=bojana
spring.datasource.password=Root.2025
# RAFLMS custom fields
raflms.gitrootdir=/home/bojana/RAFProjects/gitrepos/remote
raflms.projectrootdir=/home/bojana/raflms/projectrootdir